### ISSUE TITLE
update openwrt to 18.x

### ISSUE THREAD

**Issue by brianjmurrell** [aparcar/attendedsysupgrade-server#123]
OpenWRT at https://chef.libremesh.org/ is showing _snapshot_ as it's version.  Should it be updated to the official 18.x release?

**Comment by aparcar** [comment]
Hi @brianjmurrell please use the current development version [here](https://as-test.stephen304.com/chef/) which supports the most recent version and also snapshots. I [added a comment](https://github.com/libremesh/chef/commit/228f826a1c6a7609dbe561507e78cbf177428a67#diff-23e9f9ae758c4e158b1d71523e43be61R53) to the *official* chef version.
