### ISSUE TITLE
repair all CHEF installations

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/attendedsysupgrade-server#136]
all (two) chef-installations (mentioned on README) are out of order. please repair it. 
the first one (dev) has 404.. and the second one has an build-queue larger than 100. (and its called the dev-system by it-self, which should be the first one)

are there any other (running) instances of chef on the internet?

**Comment by FreifunkUFO** [comment]
see also https://github.com/libremesh/chef/issues/73

**Comment by aparcar** [comment]
please try chef.libremesh.org
the servers storage usage went to 100%

**Comment by FreifunkUFO** [comment]
thank you.

you were deleting the 2nd server https://github.com/aparcar/attendedsysupgrade-server/commit/f9d9846dd47f23d37697ba5db3b4ccf832679af3 so there was no chance to repair that dev-server?

**Comment by FreifunkUFO** [comment]
on chef.libremesh.org is written beta/development: 
cite "Chef Imagebuilder BETA dev"
and "Warning: This is the development version of Chef."

so, where are the stable server, which is not beta? :-o

**Comment by FreifunkUFO** [comment]
libremesh-unstable isnt working atm, but its already marked as "unstable".. (and outdated, 17.06)

**Comment by aparcar** [comment]
libremesh-unstable should be fixed via https://github.com/aparcar/attendedsysupgrade-server/commit/39de9f1e45a57c532757f317071c04319093df6a
