### ISSUE TITLE
repair CHEF installation (not moving forward)

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/attendedsysupgrade-server#139]
i found https://chef.aparcar.org as an chef-installation inside a ticket.
https://github.com/aparcar/attendedsysupgrade-server/commit/63dc132d7e89a1799a480a416cd1adcfeee39351

error-message: You're not moving forward in queue for a long time, please report this

**Comment by aparcar** [comment]
fixed via https://github.com/aparcar/attendedsysupgrade-server/pull/120/commits/d5541823e646ec279a56f876168f8adf257b75e7#diff-9e7b734aa49430924a12b528df25255e

thanks for reporting!
