### ISSUE TITLE
Unclear: What server to use for snapshot builds? Stable?

### ISSUE THREAD

**Issue by tlaurion** [aparcar/attendedsysupgrade-server#142]
Please list actual useable servers and urls. :)

Thanks!

**Comment by aparcar** [comment]
https://chef.libremesh.org
the upgrade requests go to /api/ which leads to the server

**Comment by tlaurion** [comment]
No updates, which I doubt is true. What other servers are out there? Is there a complete list?

**Comment by aparcar** [comment]
I'm on it, not trivial to manage all these

**Comment by aparcar** [comment]
it's only chef.libremesh.org until further notice
