### ISSUE TITLE
meeting with freifunk-leipzig for chef-installation

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/attendedsysupgrade-server#145]
please think about a real-life-meeting for managing and testing a chef-installations (and ass-server). 

location: leipzig (changing locations, sometimes dezentrale)
time: every thursday evening.

**Comment by FreifunkUFO** [comment]
see also 
* https://github.com/aparcar/attendedsysupgrade-server/issues/144
* https://github.com/aparcar/attendedsysupgrade-server/issues/142
* https://github.com/aparcar/attendedsysupgrade-server/issues/135
* https://github.com/aparcar/attendedsysupgrade-server/issues/138
* https://github.com/aparcar/attendedsysupgrade-server/issues/112

**Comment by aparcar** [comment]
Please request a meeting at mail [at] apracar.org

**Comment by FreifunkUFO** [comment]
hm ok, i sent an email inviting you to our jabber-chat.
