### ISSUE TITLE
too much spaces in database.py

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/attendedsysupgrade-server#154]
there are too many spaces in front of each line in that file

coming from https://github.com/aparcar/attendedsysupgrade-server/commit/a29aec84ac2cedd5af0004843a88775cb19489bc#diff-a06bf6e709c2b50d3f497ee7bda0ce57

so i got errors like that: https://gist.github.com/FreifunkUFO/ddd2bad6af0b97740a8b49fddbf48002

**Comment by FreifunkUFO** [comment]
problem is only on master-branch..

**Comment by aparcar** [comment]
yea I think I messed it slightly up with vim. will fix it once I'm back on a laptop

**Comment by aparcar** [comment]
here you go https://github.com/aparcar/attendedsysupgrade-server/commit/85d1aaf4bcd2eaea3effe3e568f62e877519a458
