### ISSUE TITLE
Unknown package in request

### ISSUE THREAD

**Issue by McChary** [aparcar/attendedsysupgrade-server#156]
![screenshot_1](https://user-images.githubusercontent.com/47784392/53021178-fda37a00-342e-11e9-9a62-72206c5a74eb.png)

when I try to create an image snapshots, this package is integrated into the list with luci, but when creating the image, that error comes out

**Comment by FreifunkUFO** [comment]
it seems that filename has changed!

from https://downloads.openwrt.org/releases/18.06.2/targets/ar71xx/tiny/packages/libgcc_7.3.0-1_mips_24kc.ipk  
to https://downloads.openwrt.org/snapshots/targets/ar71xx/tiny/packages/libgcc1_7.4.0-1_mips_24kc.ipk

so workaround for you @McChary is to rename it (via Edit Packages) from libgcc to libgcc1

**Comment by aparcar** [comment]
filename changes in a stable branch?

**Comment by aparcar** [comment]
I'm not entirely sure but I could imagine it's a problem of the upstream image builders...

**Comment by aparcar** [comment]
Should work now
