### ISSUE TITLE
link error factory

### ISSUE THREAD

**Issue by McChary** [aparcar/attendedsysupgrade-server#157]
the one from Sysupgrade seems to be good, it's straight to the download but the factory one seems to have "https://chef.libremesh.org/" added twice at the beginning of the link
![screenshot_9](https://user-images.githubusercontent.com/47784392/53152274-7d465b80-358b-11e9-9365-2fd4d677fa9d.png)

Sysupgrade
https://chef.libremesh.org/json/openwrt/snapshots/ar71xx/tiny/tl-wr841-v8/f25164be011623e/openwrt-f25164be011623e-ar71xx-tiny-tl-wr841-v8-squashfs-factory.bin

Factory
https://chef.libremesh.orghttps//chef.libremesh.org/json/openwrt/snapshots/ar71xx/tiny/tl-wr841-v8/f25164be011623e/openwrt-f25164be011623e-ar71xx-tiny-tl-wr841-v8-squashfs-factory.bin

**Comment by aparcar** [comment]
fixed via https://github.com/libremesh/chef/commit/af65b124ebcc4732f4c989249b1ce2cf07966972
