### ISSUE TITLE
linksys-wrt32x

### ISSUE THREAD

**Issue by Roland-B** [aparcar/attendedsysupgrade-server#165]
Hi, Support for the router linksys-wrt32x seems to have dissapeared from ImageBuilder normal and beta? Is it coming back soon? Thanks.

**Comment by aparcar** [comment]
possible that the target isn't activated. which one is it?

**Comment by dangowrt** [comment]
`mvevu/cortexa9`

**Comment by Roland-B** [comment]
> 
> 
> `mvebu/cortexa9`

beat me to it. Yup, mvebu/cortexa9, cheers for the quick reply.

**Comment by Roland-B** [comment]
Didnt mean to close, appologies. Issue still exists.

**Comment by aparcar** [comment]
hey, there are typos in the config file.

    - mvevu/cortexa53
    - mvevu/cortexa72
    - mvevu/cortexa9

 please correct it via a PR in ./asu/utils/distributions/openwrt/distro_config.yml

**Comment by Roland-B** [comment]
Thanks apacar, but im not running my own server im using the online ones below which are currenlty failing due to the issue reported.

https://as-test.stephen304.com/
https://chef.libremesh.org/
https://betachef.libremesh.org/

**Comment by TommyMacMoo** [comment]
I, sadly have same issue, I WRT 32X and also WRt 3200 dissapeared ...will wait...and see..if get fixed
