### ISSUE TITLE
19.07 snapshot error after selecting device

### ISSUE THREAD

**Issue by patsy1912** [aparcar/attendedsysupgrade-server#197]
**Describe the bug**

**Server URL**
Please write the URL of the server you use.

**JSON request**
Please post the JSON you've send to the server.

**Build Log** 
The server should return a build log, please post a link to the build log below.

**Expected behavior**

**Screenshots**

**Reproduce locally**
In case you could retrieve the build log, please run the lines under *BUILD COMMAND* via the [openwrt-metabuilder script](https://github.com/aparcar/meta-imagebuilder). Also possible via **Docker**

**Comment by aparcar** [comment]
Please provide some additional information as suggested by the issue template

**Comment by patsy1912** [comment]
![Screenshot_20190908-075210_Firefox_Preview](https://user-images.githubusercontent.com/19331461/64484695-0d897c80-d20e-11e9-8def-ea64835af510.png)
![Screenshot_20190908-075413_Firefox_Preview](https://user-images.githubusercontent.com/19331461/64484696-0d897c80-d20e-11e9-8600-efe403ba5969.png)
![Screenshot_20190908-075202_Firefox_Preview](https://user-images.githubusercontent.com/19331461/64484697-0e221300-d20e-11e9-9460-d2dadc9aeda3.png)

Sorry for not being clearer

On the new frontend when selecting 1907 snapshot and then selecting which device to compile for unexpected error pops up,trired on multi browsers and multiple platforms and received same error message
