### ISSUE TITLE
R7800 missing? 

### ISSUE THREAD

**Issue by sfjuocekr** [aparcar/attendedsysupgrade-server#212]
The Netgear Nighthawk X4S R7800 seems to be missing on the server

**Comment by aparcar** [comment]
Which of the many servers?

**Comment by aparcar** [comment]
![image](https://user-images.githubusercontent.com/16000931/75014423-4b7c0500-542a-11ea-9e1b-b2e2b27b1c85.png)

Please try this here https://images.aparcar.org/
