### ISSUE TITLE
make the firmware-destination editable

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/attendedsysupgrade-server#29]
when i see "new update avaiblae", i can see the prefered destination (f.i. "SNAPSHOT")

please make that textfield editable. i need the possibility to switch from LEDE-release to LEDE-trunk (and vice versa) or other firmware variation.

![att-wizawrd2](https://user-images.githubusercontent.com/2579265/29126659-436a2c8c-7d1f-11e7-9b00-c68fef182129.png)

**Comment by FreifunkUFO** [comment]
goals for instance:

- openwrt-trunk
- openwrt-release
- lede-release
- lede-trunk
- lede-trunk from last month
- lede-release with pimped wifi drivers
- lede-release with stripped symbols
- lede-trunk with enabled kernel debug symbols

**Comment by aparcar** [comment]
currently only releases and snapshots are planed. Also downgrades are not really planed. 
I could add a field to switch between _latest release_ and _snapshot_ if currently not running a snapshot.

**Comment by aparcar** [comment]
I'm not intending to support all kinds of different image builder settings, this would currently create to much overhead in the database and image requests. The server is supposed to supply images for sysupgrades, not focused on developers with custom needs.

However, if you create a patch I'd like to add this feature. If not please close this issue.

**Comment by aparcar** [comment]
Update server is now editable in latest luci-app-attendedsysupgrade, depends on the imagebuilder settings of the chosen server all variations of builds are possible
