### ISSUE TITLE
make layout great again

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/attendedsysupgrade-server#52]
the layout is getting even more worse with every change/wish.
some changes should be done for a consistent style of this project.

- [ ] there should be a small description about that package. (see other luci-subpages). of course with translations (at least for german language).

- [x] button: "search for updates" sounds inconsistent, because the headline and name of the project is "... upgrade"! so the name "updates" isnt nice.. the result of the search is not "many updates", but one "upgrade". you might change the name to "online search" to clarify the online-character of this project

- [x] the checkbox "Search for package updates": i really do not understand the purpose of that checkbox. also my problem with "updates", while the project does an "upgrade".
    a translation also would be nice. (i8n)
    if that checkbox does something during the "search" it should be ABOVE the search-button, because its an option for that search!? (see other luci-pages)

- [x] The message "imagebuilder not ready, please wait" should be in the same style as other luci-pages. please have a look at the layout of "Änderungen werden angewandt".

- [x] it also should be editabl to use a different updateserver

**Comment by FreifunkUFO** [comment]
@aparcar wrote:

It looks a bit better on the official bootstrap version, but feel free to add design suggestions :)

**Comment by aparcar** [comment]
@egon0 can you help me out?

**Comment by FreifunkUFO** [comment]
to start with the first page (without clicking the search button):

* there should be a small description about that package. (see other luci-subpages). of course with translations (at least for german language).
* button: "search for updates" sounds inconsistent, because the headline and name of the project is "... upgrade"! so the name "updates" isnt nice.. the result of the search is not "many updates", but one "upgrade". you might change the name to "online search" to clarify the online-character of this project

* the checkbox "Search for package updates": i really do not understand the purpose of that checkbox. also my problem with "updates", while the project does an "upgrade".
a translation also would be nice. (i8n)
if that checkbox does something during the "search" it should be ABOVE the search-button, because its an option for that search!? (see other luci-pages)

**Comment by aparcar** [comment]
PRs are welcome 🙄 No seriously, I'll look into that

**Comment by FreifunkUFO** [comment]
when clicking the first button:

* The message "imagebuilder not ready, please wait" should be in the same style as other luci-pages. please have a look at the layout of "Änderungen werden angewandt".

**Comment by FreifunkUFO** [comment]
@aparcar first we have to collect the problems by ticketcomments. Press Release (PR) would not be nice for that moment.

**Comment by aparcar** [comment]
Pull Requests?

**Comment by FreifunkUFO** [comment]
cite:
"Search for package updates"

so, what does it mean? 
and, what would be a nice german translation?

**Comment by aparcar** [comment]
Anwendungsaktualisierungen. however, I'm not sure how to implement translations with JavaScript.

**Comment by FreifunkUFO** [comment]
so when disabling this checkbox there are  older packages but new kernel? i dont get it.

**Comment by aparcar** [comment]
If 17.01.4 receives a package update but no new major 17.01.x release, with the option checked you simply get a new image

**Comment by egon0** [comment]
Ping 😎

**Comment by aparcar** [comment]
I'm not sure why I can not assign this directly to @egon0 , but he is the person going to solve this 👍

**Comment by FreifunkUFO** [comment]
see https://github.com/aparcar/luci/commit/9e1728cd625b841cb35de5191d82639f7bd52286

**Comment by FreifunkUFO** [comment]
having a description is nice. please change that tagging style from <p> to

<div class="cbi-map-descr">

**Comment by aparcar** [comment]
Please see https://github.com/aparcar/luci/tree/v2 for recent changes.

**Comment by FreifunkUFO** [comment]
please see https://github.com/openwrt/luci/pull/1408 for recent changes.
and @aparcar told me, new layout can be found here https://github.com/aparcar/luci/tree/v2

**Comment by aparcar** [comment]
@FreifunkUFO please excuse the "chaos", v2 was merged in acls as there already existed an PR

**Comment by FreifunkUFO** [comment]
and see https://github.com/openwrt/packages/pull/4979/files#diff-066cc010efe5ae62f0ca12bfec1e872d but its only for lede-relase (not for lede-trunk)

**Comment by aparcar** [comment]
https://github.com/openwrt/packages/pull/5053

**Comment by aparcar** [comment]
All done in latest luci version, PR is currently pending
https://github.com/openwrt/luci/pull/1437

@FreifunkUFO if translations are necessary please propose a solution, I have no experience with that

**Comment by aparcar** [comment]
@FreifunkUFO ping

**Comment by aparcar** [comment]
Closing this issue due to no response, please reopen if still relevant.
