### ISSUE TITLE
Do an automated checksum check before installing an upgrade

### ISSUE THREAD

**Issue by claell** [aparcar/attendedsysupgrade-server#76]
Title says it, thought I would open an issue here (came from https://bugs.lede-project.org/index.php?do=details&task_id=826)

**Comment by aparcar** [comment]
Thanks, currently this can only be done with md5 sums as https://github.com/openwrt/packages/pull/5118 passes I'll add sha support too

**Comment by aparcar** [comment]
@claell this is now done in https://github.com/openwrt/luci/pull/1446

**Comment by aparcar** [comment]
merged
