### ISSUE TITLE
auc: running on 17.01.3 error

### ISSUE THREAD

**Issue by aparcar** [aparcar/attendedsysupgrade-server#77]
Installed all needed packages from snapshots.

```
root@LEDE:~# auc 
Error relocating /usr/sbin/auc: uloop_run_timeout: symbol not found
```

**Comment by dangowrt** [comment]
You can't use the binaries from snapshot on 17.01. because libubox
has evolved since.
Use the SDK 17.01 to build the package from source (that's what I did
for x86_64 during development).

**Comment by aparcar** [comment]
Thanks for the clarification
