### ISSUE TITLE
server should return more details on error 

### ISSUE THREAD

**Issue by dangowrt** [aparcar/attendedsysupgrade-server#78]
Currently the server returns `400` in all three cases:
 * request is malformed (syntax/parser error) => here `400` is appropriate
 * request is well formated but contains an unknown package => `422` would be more appropriate
 * request is well formated but requests an image for an unknown board => `412` would be more appropriate

**Comment by aparcar** [comment]
Unknown distro, unknown release, unsupported device, build error, image size error (image to big), más? 
Ideas for these as well?
