### ISSUE TITLE
boardnames may be quirky

### ISSUE THREAD

**Issue by dangowrt** [aparcar/attendedsysupgrade-server#80]
In some (legacy) targets there are cases of the board_name reported on the target doesn't match the profile name in the image generation code. Most popular examples are
`ar71xx/generic/ubnt-nanostation-m` on target should be replaced by `ar71xx/generic/ubnt-nano-m`
`ar71xx/generic/ubnt-nanostation-m-xw` on target should be replaced by `ar71xx/generic/ubnt-nano-m-xw`
Other examples are
`ramips/mt7620/psg1218` on target running lede-17.01 should be replaced by `ramips/mt7620/psg1218a` or `ramips/mt7620/psg1218b` in newer releases.

So this is somehow similar to the package name transformations, just not that complex...

**Comment by aparcar** [comment]
@dangowrt who to solve the `psg1218{a, b}` situation? Need more context
