### ISSUE TITLE
How to use this with LEDE?

### ISSUE THREAD

**Issue by claell** [aparcar/attendedsysupgrade-server#82]
I am interested in using this for my LEDE installation, but don't know exactly how to integrate it. Do I simply need to install `luci-app-attendedsysupgrade` in LEDE?

Also since this seems pretty helpful, are there plans to integrate it directly into all LEDE installations?

**Comment by aparcar** [comment]
Thanks for your interest. Yes, currently you can install `luci-app-attendedsysupgrade` or `auc` (for cli) from a snapshot build.

There have been some recent affords to bring this into the stable repository of LEDE, but there is still some work to do. This step would make it easy installable via opkg. 

>Also since this seems pretty helpful, are there plans to integrate it directly into all LEDE installations?

I'd really like the idea but as this is still a young project the server would just die if used on high scale. Currently I'm trying to improve the performance to be eventually suitable for an official service.

**Comment by claell** [comment]
Ah ok. Currently I am using the stable version, so I will wait until it becomes available there.

So you are running an own server for this? I thought it could simply use the LEDE servers.

**Comment by aparcar** [comment]
@claell yes this runs on a private VM. However if it's ever stable and scales, I'll ask to run this on official servers.

I'll close the issue as it should be resolved?

**Comment by claell** [comment]
Yes, you can close this. Is this in the official repositories already, or do I have to wait a bit?

**Comment by claell** [comment]
Alright, will wait for it then
