### ISSUE TITLE
trunk: Failed to execute template dispatcher target for entry '/admin/system/attended_sysupgrade'

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/attendedsysupgrade-server#87]
on a c59 with meshkit (lede-trunk from yesterday) i got an error:

http://10.61.93.111/cgi-bin/luci//admin/system/attended_sysupgrade/

/usr/lib/lua/luci/dispatcher.lua:478: Failed to execute template dispatcher target for entry '/admin/system/attended_sysupgrade'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'attendedsysupgrade'.
A runtime error occured: [string "/usr/lib/lua/luci/view/attendedsysupgrade.h..."]:12: bad argument #1 to 'parse' (string expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:478: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by aparcar** [comment]
Can you reproduce the error with an locally installed ImageBuilder? Does this error appear in stable?

**Comment by FreifunkUFO** [comment]
i dont know how to reproduce. maybe someone should test it with "normal" lede-trunk?

as said before: my test was on "locally installed" (on freifunk-leipzig meshkit server) imagebuilder (aka meshkit), where the imagebuilder also was "locally built" (on 11.1.2018).

what does "stable" means, is it lede-17.01.4?
i never tested that version.

**Comment by aparcar** [comment]
@FreifunkUFO is this still relevant?

**Comment by aparcar** [comment]
Closed due to no response
